package com.sergec.drivemonitor;
import android.app.*;import android.os.*;import android.graphics.Color;import android.view.*;import android.widget.*;import java.net.*;import java.io.*;import java.time.*;import java.time.format.*;import java.util.*;import java.util.concurrent.*;import org.json.JSONObject;
public class MainActivity extends Activity{
 Handler h=new Handler(Looper.getMainLooper()); ExecutorService ex=Executors.newSingleThreadExecutor(); Random rnd=new Random(); LinearLayout cards; TextView name,src,time,err; Switch live; boolean busy;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(ui());tick.run();}
 View ui(){ScrollView s=new ScrollView(this);s.setBackgroundColor(Color.rgb(11,18,32));LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(20),dp(25),dp(20),dp(30));name=t("PF753-CUTTER-01",27,Color.WHITE,true);r.addView(name);r.addView(t("DRIVE CONDITION MONITOR",12,Color.rgb(70,170,255),true));live=new Switch(this);live.setText("Use live Django API");live.setTextColor(Color.WHITE);live.setPadding(0,dp(18),0,dp(10));r.addView(live);src=t("Source: DEMO DATA",13,Color.LTGRAY,false);time=t("Updated: --",13,Color.LTGRAY,false);err=t("",13,Color.rgb(255,110,110),false);r.addView(src);r.addView(time);r.addView(err);cards=new LinearLayout(this);cards.setOrientation(LinearLayout.VERTICAL);cards.setPadding(0,dp(12),0,0);r.addView(cards);TextView n=t("Demo mode refreshes every 2 seconds. Live mode reads the URL configured in app/build.gradle.kts.",12,Color.rgb(150,165,190),false);n.setPadding(0,dp(15),0,0);r.addView(n);s.addView(r);return s;}
 Runnable tick=new Runnable(){public void run(){if(live.isChecked())api();else show(fake(),"DEMO DATA","");h.postDelayed(this,2000);}};
 JSONObject fake(){try{boolean run=rnd.nextDouble()>.12;JSONObject j=new JSONObject();j.put("drive_name","PF753-CUTTER-01");j.put("status",run?"RUNNING":"STOPPED");j.put("output_frequency_hz",run?35+rnd.nextDouble()*15:0);j.put("output_current_a",run?4+rnd.nextDouble()*6:0);j.put("dc_bus_voltage_v",635+rnd.nextDouble()*25);j.put("motor_speed_rpm",run?1050+rnd.nextInt(450):0);j.put("elapsed_runtime_hours",2374.6+rnd.nextDouble());j.put("temperature_c",36+rnd.nextDouble()*12);j.put("timestamp",Instant.now().toString());return j;}catch(Exception e){return new JSONObject();}}
 void api(){if(busy)return;busy=true;ex.execute(()->{try{HttpURLConnection c=(HttpURLConnection)new URL(BuildConfig.DRIVE_API_URL).openConnection();c.setConnectTimeout(5000);c.setReadTimeout(5000);c.setRequestProperty("Accept","application/json");if(c.getResponseCode()/100!=2)throw new Exception("HTTP "+c.getResponseCode());BufferedReader q=new BufferedReader(new InputStreamReader(c.getInputStream()));StringBuilder z=new StringBuilder();String x;while((x=q.readLine())!=null)z.append(x);JSONObject j=new JSONObject(z.toString());runOnUiThread(()->show(j,"DJANGO API",""));}catch(Exception e){runOnUiThread(()->show(fake(),"DEMO FALLBACK","API unavailable: "+e.getMessage()));}finally{busy=false;}});}
 void show(JSONObject j,String source,String error){name.setText(j.optString("drive_name","Drive Monitor"));src.setText("Source: "+source);err.setText(error);String ts=j.optString("timestamp",Instant.now().toString());try{ts=DateTimeFormatter.ofPattern("dd MMM yyyy  HH:mm:ss").withZone(ZoneId.systemDefault()).format(Instant.parse(ts));}catch(Exception ignored){}time.setText("Updated: "+ts);cards.removeAllViews();String st=j.optString("status","UNKNOWN");card("Drive status",st,st.equals("RUNNING")?Color.rgb(60,210,130):Color.rgb(255,190,70));card("Output frequency",f(j,"output_frequency_hz","Hz"),Color.WHITE);card("Output current",f(j,"output_current_a","A"),Color.WHITE);card("DC bus voltage",f(j,"dc_bus_voltage_v","V"),Color.WHITE);card("Motor speed",j.optInt("motor_speed_rpm")+" RPM",Color.WHITE);card("Elapsed runtime",f(j,"elapsed_runtime_hours","h"),Color.WHITE);card("Drive temperature",f(j,"temperature_c","°C"),Color.WHITE);}
 String f(JSONObject j,String k,String u){return String.format(Locale.US,"%.1f %s",j.optDouble(k),u);}void card(String l,String v,int col){LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(dp(18),dp(15),dp(18),dp(15));c.setBackgroundColor(Color.rgb(24,35,54));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,dp(10));cards.addView(c,p);c.addView(t(l.toUpperCase(Locale.ROOT),11,Color.rgb(150,165,190),true));c.addView(t(v,25,col,true));}
 TextView t(String s,int z,int c,boolean b){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setTextColor(c);if(b)v.setTypeface(null,1);return v;}int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}protected void onDestroy(){h.removeCallbacks(tick);ex.shutdownNow();super.onDestroy();}}
